### ISSUE TITLE
In-line parameters for operations

### ISSUE THREAD

**Issue by jpy-luke** [lukefi/metsi#3]
The current multiparameter system is only suitable for declaring full alternative parameter sets for an operation within an alternatives generator. This is not granular enough nor extensible enough. Users desire the ability to declare parameters directly upon the operations. This will also better support upcoming operation alias system.

Here's an overall new proposal:

```yaml
operation_params:
  operation1: # only define a single, optional set of default parameters for each operation instead of a list
    param1: 1
    param2: 2
simulation_events:
  - time_points: [0]
  - generators:
    - sequence:
      - operation1 # uses default parameters
      - operation1:
        - param1: 2 # partially overrides default parameters
      - operation1:
        - param1: 5 # fully overrides default parameters
          param2: 7
        - param1: 8 # problem: what should we do with sequence operations that get multiple parameters?
      - alternatives:
        - operation1: # branches into two operation1 calls with different partially overridden parameters
          - param1: 20
          - param2: 30 
        - operation2 # has no default parameters
        - operation2:
          - param3: 233 # set something that the operation 2 is known to support
```

I propose that we replace the current "list of default parameter objects" with a single "object of default parameters" for each operation. Optionality of declaring this would be dependent on requirements of the operation. This would be the cleanest thing to implement and would eliminate ambiguity introduced by in-line parameters if the current implementation is used.

This way we can then partially or fully override parameter sets in-line if need be. Alternatives branching logic would no longer depend upon alternative parameter sets declared on the higher level. It could be done more precisely in-line with partial overriding of the default.

Still remains the problem of attempting to introduce multiple parameters for an operation in a sequence. Currently we raise an Exception in this case. The multiple parameters list was introduced solely for the use of alternatives. We could simply leave it as an option for the user to be able to do many repeated calls to the same operation with different parameters.
