### ISSUE TITLE
Transition event sequence

### ISSUE THREAD

**Issue by jpy-luke** [lukefi/metsi#4]
Currently the simulation events that mean transition from one time point to the next need to be declared either at the very beginning or at the very end of the simulation events declaration. While this does achieve the effect of transitioning from one time point to another, it can be an unnecessary complexity to work with when designing simulation events. It also forces us to declare specific time points that the transition is supposed to happen for.

Transition could be automated. Transitioning from one time point to another, and determining what amount of time points thus elapses, could be calculated from the time points list derived from the declaration. This might be a varying amount of years, so #3 is needed for this work.

Then, the implementation needs to either

* manipulate the simulation events declaration on the application level so that the growth years block is generated based on another new declaration in the control file
* time step transitioning is made as a simulator level feature so that the engine itself makes a separation between transition sequence and other events. I am in favour of this, since it is essentially a very generic feature that every discrete time step simulator needs. It would also open up the possibility for the application to source the transition from any source instead of just the combination of simulation events declaration and domain operations.

New declaration (crafted funnily purposefully would look something like:

```yaml
transition_sequence:
  - grow

simulation_events:
  - time_points: [2020, 2029, 2031] # block 1
    generators:
      - sequence:
        - compute_something
      - alternatives:
        - thinning1
        - thinning2
  - time_points: [2021, 2027, 2029, 2050] # block 2
    generators:
      - sequence:
        - compute_anotherthing 
```

This would result in a simulation where transition sequence would automatically happen as follows
2020 -> 2021, step 1 year
2021 -> 2027, step 6 years
2027 -> 2029, step 2 years
2029 -> 2031, step 2 years
2031 -> 2050, step 19 years

Then within each actual time point, the simulation events are executed like they already do.
Step sequence for the transition even can be generated with the `lukefi.metsi.sim.generators.NestableGenerator`.
Applying the sequence needs to be implemented on the level of the run strategies in `lukefi.metsi.sim.runners`
