### ISSUE TITLE
Operation aliases

### ISSUE THREAD

**Issue by jpy-luke** [lukefi/metsi#5]
To give a choice against cluttering the simulation events tree with in-line parameters made in #3, allow the declaration of operation aliases. Operation aliases are resolvable from a map and point to an actual operation with an optionally given set of parameters that overrides the operation's possible default parameters. The parameter sets would then establish a line of precedence: in-line -> alias -> default.

Simply to put in yaml terms:

```yaml
operation_params:
  first_thinning:
    param1: 123
    param2: 234

operation_aliases:
  first_thinning11:
    first_thinning:
      param1: 567
  first_thinning12:
    first_thinning:
      param2: 345
  first_thinning13:
    first_thinning:
      param1: 990
      param2: 345

simulation_events:
  - time_points: [1, 2, 3]
    generators:
      alternatives:
        - first_thinning11
        - first_thinning12
        - first_thinning13
        - first_thinning13:
          - param2: 999
          - param1: 666
```

this would result in creating 5 branches for first_thinning with following parameter pairs in order of apparance:
567, 234
123, 345
990, 345
990, 999
666, 345

This support needs to be built via lukefi.metsi.sim.core_types.SimConfiguration and lukefi.metsi.sim.generators.NestableGenerator
