### ISSUE TITLE
Universal conditional run evaluator for operations

### ISSUE THREAD

**Issue by jpy-luke** [lukefi/metsi#6]
We want to allow users to declare arbitrary state-matched run conditions for operations within the control file. When the condition evaluates falsely, the branch will abort.

Consider the following yaml snippet of in-line parameters:

```yaml
  - first_thinning:
    # default case
    - minimum_removal: 400
      min_mean_diameter_before: 3
    # condition case 1
    - condition: forest_management_category == 1 and soil_and_peatland_category ==1
      minimum_removal: 400
      min_mean_diameter_before: 8
```

It would be possible to create a common evaluator function which can be given as an argument to prepared operations.

* During the lukefi.metsi.sim.generators.NestableGenerator operation preparation, if the operation has the `condition` parameter, prepare a predicate function `(CUType) => bool`  which evaluates the condition parameter string against the CUType object as the global namespace. Draw upon `lukefi.metsi.domain.utils.collectives` for how it's done and how `lukefi.metsi.domain.pre_ops.applyfilter` applies this for predicating.
* Inject this function as a callable into the creation of the prepared operation as a  `processor`. Default shall be `lambda: True`
* Call the function in the processor and raise UserWarning if the predicate returns False.
