### ISSUE TITLE
Inter-operation timing constraints

### ISSUE THREAD

**Issue by jpy-luke** [lukefi/metsi#7]
Currently, on the simulator level, we allow a single restriction for any single operation. thinning_from_above blocks thinning_from_above for 20 years:

```yaml
run_constraints:
  thinning_from_above:
    minimum_time_interval: 20
```

This results in branch execution being cut off before the operation gets called, if thinning_from_above was already called within the previous 20 time points. This exists to ease off having to make each operation to implement their own logic for checking this.

There are constraints that could also apply between different operations. Examples could be that :
* there is no sense in attempting `first_thinning` or other thinnings within N years from `clearcutting`
* there is no sense in doing `plant` if `clearcutting` was not done within M years

For these, the run_constraints structure could be expanded to become a list of constraints, which expand into a 1:N constrained operations.

```yaml
run_constraints:
  first_thinning:
    blocked_after:
      clearcutting: 20
  thinning_from_below:
    blocked_after:
      clearcutting: 30
```

Or alternatively
```yaml
run_constraints:
  clearcutting:
    blocks:
      first_thinning: 20
      thinning_from_below: 30
```

These could be declared to establish both constraints between any operations
```yaml
run_constraints:
  clearcutting:
    blocks:
      first_thinning: 20 # clearcutting blocks first thinning for 20 years
      thinning_from_below: 30 # clearcutting blocks thinning from below for 20 years
    blocked_after:
      clearcutting: 100 # clearcutting blocked after clearcutting for 100 years
  thinning_from_below:
    blocked_after:
      first_thinning: 15 # thinning from below blocked after first thinning for 15 years
      clearcutting: 40 # thinning from below blocked after clearcutting for 40 years
  cross_cut_whole_stand:
    blocks:
      cross_cut_whole_stand: 1 # cross_cut_whole_stand blocks cross_cut_whole_stand for 1 years
```

if there is a blocks and blocked_after constraints between any two operations, both conditions must match to be able to run.

Implement must work with operation aliases from #5 
Inspection logic for this should go into `lukefi.metsi.sim.operations.check_operation_is_eligible_to_run`
