### ISSUE TITLE
Named generator blocks

### ISSUE THREAD

**Issue by jpy-luke** [lukefi/metsi#8]
To further be able to simplify and manage complexity of the main simulation_events tree, we can implement named generator blocks. Operations in the example below can be aliased operations from #5.

The yaml examples illustrate this:

2. Create a simulator pre-flight feature that uses a pre-set structure to resolve aliases:
```yaml
    named_generators:
      seeding_alternatives:
        alternatives:
          - seed:
            - species: 'pine'
              spread: 0.3
            - species: 'birch'
              spread: 0.2
      seed_pine:
        sequence:
          - seed:
            - species: 'pine'
              spread: 0.3           
      seed_birch:
        sequence:
          - seed:
            - species: 'birch'
              spread: 0.2

    simulation_events:
      - time_points: [0]
        generators:
          - seeding_alternatives
          - seed_pine
          - seed_birch
```

This would become a structure equivalent to
```yaml
    simulation_events:
      - time_points: [0]
        generators:
          - alternatives:
            - seed:
              - species: 'pine'
                spread: 0.3
              - species: 'birch'
                spread: 0.2
          - sequence:
            - seed:
              - species: 'pine'
                spread: 0.3
          - sequence:
            - seed:
              - species: 'birch'
                spread: 0.2
```

This would essentially be a simple implementation into `lukefi.metsi.sim.core_types.SimConfiguration` or perhaps `lukefi.metsi.sim.generators.NestableGenerator` to substitute encountered generator aliases with the object resolved from named_generators.
